language: node_js

node_js:
  - "lts/*"

cache:
  yarn: true

install:
  - yarn global add codecov
  - yarn install

script:
  - yarn eslint src
  - yarn flow
  - yarn test -- --coverage
  - yarn build

before_deploy:
  - yarn build-storybook

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: storybook-static
  on:
    branch: master

after_script:
  - codecov