language: node_js

node_js:
  - "lts/*"

cache:
  yarn: true

install:
  - yarn global add codecov
  - yarn install

script:
  - yarn eslint src
  - yarn flow
  - yarn test -- --coverage
  - yarn build

after_success:
  - yarn deploy

after_script:
  - codecov